# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AKbKQf6cL6WDh1qNb2cIvURCnZ4Uk6L-
"""

import streamlit as st
import pandas as pd
import altair as alt

# Load and clean data
file_id = '1C2dq7vFPWD37RSHDK2r3qBmaeCeKrNLZ'  # Replace with your actual file ID
url = f'https://drive.google.com/uc?id={file_id}'
df = pd.read_csv(url)

df = df[[
    'name', 'neighbourhood_cleansed', 'room_type', 'price', 'number_of_reviews',
    'review_scores_rating', 'minimum_nights', 'availability_365', 'accommodates'
]].copy()

df['price'] = df['price'].replace('[\$,]', '', regex=True).astype(float)
df = df.dropna(subset=['price', 'review_scores_rating', 'room_type', 'neighbourhood_cleansed'])
df = df[df['price'] > 0]

# Sidebar filters
st.sidebar.header("Filters")
neighborhoods = ['All'] + sorted(df['neighbourhood_cleansed'].unique())
neighborhood = st.sidebar.selectbox("Neighborhood", neighborhoods)
room_types = st.sidebar.multiselect("Room Type(s)", options=df['room_type'].unique(), default=list(df['room_type'].unique()))
price_range = st.sidebar.slider("Price Range (¥)", int(df['price'].min()), int(df['price'].max()), (5000, 100000))
score_range = st.sidebar.slider("Review Score Range", 1.0, 5.0, (3.0, 5.0), step=0.1)

# Apply filters
df_filtered = df[
    (df['room_type'].isin(room_types)) &
    (df['price'] >= price_range[0]) & (df['price'] <= price_range[1]) &
    (df['review_scores_rating'] >= score_range[0]) & (df['review_scores_rating'] <= score_range[1])
]
if neighborhood != 'All':
    df_filtered = df_filtered[df_filtered['neighbourhood_cleansed'] == neighborhood]

# Title
st.title("Tokyo Airbnb Dashboard")
st.write("Explore Tokyo's Airbnb listings by filtering by room type, price, score, and neighborhood.")
st.write(f"🔍 **Filtered Listings:** {len(df_filtered)}")

# Optional debug table
# st.dataframe(df_filtered)

if df_filtered.empty:
    st.warning("⚠️ No listings match your current filter settings. Try broadening your selection.")
else:
    # Chart 1: Count of listings by room type and neighborhood
    room_bar = alt.Chart(df_filtered).mark_bar().encode(
        x=alt.X('count():Q', title='Number of Listings'),
        y=alt.Y('neighbourhood_cleansed:N', sort='-x', title='Neighborhood'),
        color='room_type:N',
        tooltip=['room_type:N', 'count():Q']
    ).properties(
        width=600,
        height=300,
        title="Listings by Room Type and Neighborhood"
    )

    # Chart 2: Scatterplot of Price vs. Review Score
    scatter1 = alt.Chart(df_filtered).mark_circle(size=60).encode(
        x=alt.X('review_scores_rating:Q', title='Review Score'),
        y=alt.Y('price:Q', title='Price (¥)'),
        color='room_type:N',
        tooltip=['name:N', 'price:Q', 'review_scores_rating:Q', 'room_type:N']
    ).interactive().properties(
        width=600,
        height=300,
        title="Price vs. Review Score"
    )

    # Chart 3: Scatterplot of Accommodates vs. Price
    scatter2 = alt.Chart(df_filtered).mark_circle(size=60).encode(
        x=alt.X('accommodates:Q', title='Accommodates'),
        y=alt.Y('price:Q', title='Price (¥)'),
        color='room_type:N',
        tooltip=['name:N', 'price:Q', 'accommodates:Q', 'room_type:N']
    ).interactive().properties(
        width=600,
        height=300,
        title="Price vs. Accommodates"
    )

    # Display charts
    st.altair_chart(room_bar, use_container_width=True)
    st.altair_chart(scatter1, use_container_width=True)
    st.altair_chart(scatter2, use_container_width=True)